### ISSUE TITLE
Make a Server

### ISSUE THREAD

**Issue by MorganJamesSmith** [MMarsland/TFTPFileTransfer#1]
# Server Specification 

The server will be implemented as a Java program that consists of multiple Java threads. The server must be capable of supporting multiple concurrent read and write connections with different clients. To accomplish this, the server will have a multithreaded architecture. One thread will wait on port 69 (the "well-known port" for TFTP) for UDP datagrams (that should contain RRQ or WRQ packets). This thread should: 

1. create another thread (call it the client connection thread), and pass it the TFTP packet to deal with; and 
2. go back to waiting on port 69 for another request. 

The newly created client connection thread will be responsible for communicating 

Once started, the TFTP server will run until it receives a “shutdown” command from the server operator. Note that the server operator will type in this request in the server window. It is neither desirable nor acceptable for a client to request that the server shutdown. After being told to shut down, the server should finish all file transfers that are currently in progress, but refuse to create new connections with clients.

**Comment by MMarsland** [comment]
Server Functionally Complete. May need tuning as it is tested with the Client and ErrorSim. Need to remove Debugging Comments.

**Comment by MMarsland** [comment]
Server Complete for Iteration #1
