### ISSUE TITLE
Package and ZIP all deliverable and submit

### ISSUE THREAD

**Issue by MMarsland** [MMarsland/TFTPFileTransfer#22]

**Comment by MMarsland** [comment]
Server State Diagrams:
![Server State Diagram-Listener](https://user-images.githubusercontent.com/37355199/58817908-d1d18c00-85fa-11e9-815a-9340279bebdb.png)
![Server State Diagram-Main](https://user-images.githubusercontent.com/37355199/58817909-d26a2280-85fa-11e9-8689-d60b5a8c40ad.png)
![Server State Diagram-ReadHandler](https://user-images.githubusercontent.com/37355199/58817910-d26a2280-85fa-11e9-9093-ae052d2f9b6b.png)
![Server State Diagram-WriteHandler](https://user-images.githubusercontent.com/37355199/58817911-d26a2280-85fa-11e9-9e2c-92c27e06d2d5.png)

**Comment by MorganJamesSmith** [comment]
![sequence-diagram-error5](https://user-images.githubusercontent.com/25649634/58818517-1a3d7980-85fc-11e9-8c46-976888e44699.png)
![sequence-diagram-error4-server](https://user-images.githubusercontent.com/25649634/58818518-1a3d7980-85fc-11e9-9d0c-ae9e4038a8b0.png)
![sequence-diagram-error4-client](https://user-images.githubusercontent.com/25649634/58818519-1a3d7980-85fc-11e9-9361-bac257d2154a.png)

**Comment by ScottMalonda** [comment]
[3303 Client State Machine Itt. 3.pdf](https://github.com/MMarsland/TFTPFileTransfer/files/3248565/3303.Client.State.Machine.Itt.3.pdf)

**Comment by JasonNyentap** [comment]
[ErrorSim IT3.pdf](https://github.com/MMarsland/TFTPFileTransfer/files/3248572/ErrorSim.IT3.pdf)

ErrorSim state diagram

**Comment by Pepuka** [comment]
[Client-side File Error Diagrams.pdf](https://github.com/MMarsland/TFTPFileTransfer/files/3272694/Client-side.File.Error.Diagrams.pdf)

**Comment by MorganJamesSmith** [comment]
iteration3 was submitted
