### ISSUE TITLE
Assemble Iteration 4 Diagrams

### ISSUE THREAD

**Issue by ScottMalonda** [MMarsland/TFTPFileTransfer#24]

**Comment by MMarsland** [comment]
Server - Sequence Diagrams for the Errors
![FileNotFound(Read)](https://user-images.githubusercontent.com/37355199/59210857-83813780-8b7c-11e9-9c54-60f9cdd9506e.png)
![FileNotFound(Write)](https://user-images.githubusercontent.com/37355199/59210858-83813780-8b7c-11e9-946a-b79aad61a176.png)
![AccessViolation(Read)](https://user-images.githubusercontent.com/37355199/59210859-83813780-8b7c-11e9-9a24-eff857b4ed72.png)
![AccessViolation(Write)](https://user-images.githubusercontent.com/37355199/59210860-83813780-8b7c-11e9-9a34-d0b78a3b6c4a.png)
![DiskFull(Write-During)](https://user-images.githubusercontent.com/37355199/59210861-8419ce00-8b7c-11e9-883c-e2643cef1c73.png)
![DiskFull(Write-Start)](https://user-images.githubusercontent.com/37355199/59210862-8419ce00-8b7c-11e9-9a00-7661dfc77356.png)

**Comment by MMarsland** [comment]
Server - State Diagrams
![Server State Diagram-ReadHandler](https://user-images.githubusercontent.com/37355199/59210899-9dbb1580-8b7c-11e9-88bb-281933cfea8b.png)
![Server State Diagram-WriteHandler](https://user-images.githubusercontent.com/37355199/59210900-9e53ac00-8b7c-11e9-95e9-da6f4da04621.png)
![Server State Diagram-Listener](https://user-images.githubusercontent.com/37355199/59210901-9e53ac00-8b7c-11e9-93c7-c2eead830fca.png)
![Server State Diagram-Main](https://user-images.githubusercontent.com/37355199/59210902-9e53ac00-8b7c-11e9-9593-2b7128de774f.png)

**Comment by MMarsland** [comment]
plantUML Source Code
[Server State Diagram-ReadHandler.txt](https://github.com/MMarsland/TFTPFileTransfer/files/3272935/Server.State.Diagram-ReadHandler.txt)
[Server State Diagram-WriteHandler.txt](https://github.com/MMarsland/TFTPFileTransfer/files/3272936/Server.State.Diagram-WriteHandler.txt)
[Server State Diagram-Listener.txt](https://github.com/MMarsland/TFTPFileTransfer/files/3272937/Server.State.Diagram-Listener.txt)
[Server State Diagram-Main.txt](https://github.com/MMarsland/TFTPFileTransfer/files/3272938/Server.State.Diagram-Main.txt)
[FileNotFound(Read).txt](https://github.com/MMarsland/TFTPFileTransfer/files/3272941/FileNotFound.Read.txt)
[FileNotFound(Write).txt](https://github.com/MMarsland/TFTPFileTransfer/files/3272942/FileNotFound.Write.txt)
[AccessViolation(Read).txt](https://github.com/MMarsland/TFTPFileTransfer/files/3272943/AccessViolation.Read.txt)
[AccessViolation(Write).txt](https://github.com/MMarsland/TFTPFileTransfer/files/3272944/AccessViolation.Write.txt)
[DiskFull(Write-During).txt](https://github.com/MMarsland/TFTPFileTransfer/files/3272945/DiskFull.Write-During.txt)
[DiskFull(Write-Start).txt](https://github.com/MMarsland/TFTPFileTransfer/files/3272946/DiskFull.Write-Start.txt)

**Comment by ScottMalonda** [comment]
[Client-side File Doesn't Exist Sequence Diagram.pdf](https://github.com/MMarsland/TFTPFileTransfer/files/3272925/Client-side.File.Doesn.t.Exist.Sequence.Diagram.pdf)
[Client-side File Access Violation Diagram.pdf](https://github.com/MMarsland/TFTPFileTransfer/files/3272926/Client-side.File.Access.Violation.Diagram.pdf)

**Comment by ScottMalonda** [comment]
[Client-side File Access Violation (Read request).pdf](https://github.com/MMarsland/TFTPFileTransfer/files/3272952/Client-side.File.Access.Violation.Read.request.pdf)
[Client-side Disk Full (RRQ).pdf](https://github.com/MMarsland/TFTPFileTransfer/files/3272973/Client-side.Disk.Full.RRQ.pdf)

**Comment by JasonNyentap** [comment]
Use Case Diagram
[Use Case Diagram.pdf](https://github.com/MMarsland/TFTPFileTransfer/files/3272997/Use.Case.Diagram.pdf)

**Comment by ScottMalonda** [comment]
[3303 Client State Machine Itt. 4.pdf](https://github.com/MMarsland/TFTPFileTransfer/files/3273072/3303.Client.State.Machine.Itt.4.pdf)

**Comment by MorganJamesSmith** [comment]
submitted iteration 4
