### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by MorganJamesSmith** [MMarsland/TFTPFileTransfer#3]
# User Interface 
You must implement both a "quiet" and a "verbose" mode. While a real-world system would not output detailed information, we need the "verbose" mode to ensure the system is functioning correctly. In "verbose" mode the client, error simulator, and server output detailed information about packets received and sent, as well as any timeouts and/or retranmission of packets. The detailed packet information must 
include:  
• whether the packet was sent or received (including any information about 
timeouts and/or retransmits, as appropriate);  
• packet type (i.e. RRQ, WRQ, DATA, ACK, ERROR);  
• filename (if applicable);  
• mode (if applicable);  
• block number as an integer (0 to 65535; if applicable);  
• number of bytes of data (0 to 512; if applicable), but not the actual data. 
Keep the user interface (UI) simple. Reduce the amount of input required each time by having options to change values, rather than having to input them each time (e.g. an option to toggle between "quiet" to "verbose" mode). To avoid confusion, keep things consistent with the specification when appropriate, e.g. use option 1 for RRQ and 2 for WRQ, rather than vice versa.

A GUI is neither recommended nor required! Do not develop a fancy UI 
comprised of instances of JButton, JList, JComboBox, JCheckBox, etc., etc., etc., for two reasons. First, developing a fancy UI is not the focus of this project. You should instead direct your efforts to ensuring that the programs correctly implement TFTP (how will you test ERROR packet creation and handling? How will you test the timeout/retransmit protocol?). Second, most of the methods in the Swing classes are not thread-safe. This means that mutual exclusion is not enforced if user-defined threads and Swing's event-dispatching thread invoke methods in Swing classes concurrently. You should be able to build an adequate UI using regular text windows or by using one or more JTextArea objects (possibly placed in JScrollPane objects) and various types of dialog boxes that can be created by class JOptionPane. The append() method in JTextArea is one of the few Swing methods that is guaranteed 
to be thread-safe. You should review the JTextArea API to see if there are any other 
thread-safe methods that may be of use. Some notes about JOptionPane will be posted 
on the course Web site. If you choose to use any features not mentioned above, you 
must provide a detailed explanation in your documentation as to the research you did 
and the reasoning process you went through to convince yourselves that the 
additional features you used are indeed thread-safe. This will likely not be a trivial

**Comment by ScottMalonda** [comment]
Client is functional assuming no errors occur
